### ISSUE TITLE
Poor Performance under sparse sampling of the world space

### ISSUE THREAD

**Issue by ac101m** [KaptainWutax/BiomeUtils#11]
First I want to thank you for publishing and maintaining this repository, it's certainly made my life a lot easier!

I'm currently implementing a tool for finding biomes which performs sparse sampling of the worldspace in order to cut down the total number of samples. I've found that doing this causes the performance of BiomeUtils to drop off pretty drastically (from millions of samples per second to mere tens of thousands).

Here is some test data (resolution=7 -> every 128th block) (each test involves the same number of samples):
```
Resolution  Samples     duration    Samples/s   sqkm/s
0           262144      109.223ms   2.400M      2.400       
1           262144      349.795ms   749.422k    2.998       
2           262144      746.277ms   351.269k    5.620       
3           262144      988.557ms   265.179k    16.971      
4           262144      1.359s      192.895k    49.381      
5           262144      2.306s      113.670k    116.398     
6           262144      3.325s      78.848k     322.961     
7           262144      4.453s      58.863k     964.407     
8           262144      5.548s      47.251k     3.097k      
9           262144      6.956s      37.688k     9.880k 
```

Is this something that can be mitigated, or is it just an unavoidable consequence of how the code works?

**Comment by KaptainWutax** [comment]
This is normal. Closer regions are faster to compute because the output of the layers is cached. Though generally, when you are doing sparse sampling, you inevitably end up doing fewer samples which increase performance drastically. If you explain your use case I might be able to point you to specific optimizations you can make. Cheers!

**Comment by ac101m** [comment]
After writing this comment I spent some time time looking in more depth at how biome generation works and ended up coming to more or less the same conclusion.
Later I came across a C library that does more or less the same thing. As C & C++ are languages I'm more familiar with, I'll probably end up using that for my project instead. (sorry!)
